#pragma once

#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cctype>
#include <ctime>
#include <deque>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <ios>
#include <iterator>
#include <locale>
#include <memory>
#include <mutex>
#include <optional>
#include <ostream>
#include <ranges>
#include <sstream>
#ifndef __cpp_lib_atomic_shared_ptr
#include <stdatomic.h>
#endif
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <QAbstractListModel>
#include <QAbstractTableModel>
#include <QByteArray>
#include <QClipboard>
#include <QColor>
#include <QCoreApplication>
#include <QDateTime>
#include <QDebug>
#include <QGuiApplication>
#include <QHash>
#include <QLocale>
#include <QMessageLogContext>
#include <QModelIndex>
#include <QNetworkReply>
#include <QObject>
#include <QPixmap>
#include <QQmlApplicationEngine>
#include <QQuickImageProvider>
#include <QScopedPointer>
#include <QSize>
#include <QSortFilterProxyModel>
#include <QStandardPaths>
#include <QString>
#include <QStringList>
#include <QStringView>
#include <QTimer>
#include <QVariant>
#include <Qt>
#include <QtLogging>
#include <qqml.h>

#ifdef ANDROID
#include <QFuture>
#include <QJniEnvironment>
#include <QJniObject>
#include <QTimeZone>
#include <QtCore/private/qandroidextras_p.h>
#endif

#include <nlohmann/json.hpp>
