cmake_minimum_required(VERSION 3.28.3)
project("WebDAV Client" VERSION 1.0 LANGUAGES CXX)
include(GNUInstallDirs)
include(CMakePrintHelpers)
set(ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR})
cmake_print_variables(ROOT_PATH)
set(COMMON_SRC ${ROOT_PATH}/src/Common)
cmake_print_variables(COMMON_SRC)

set(WDC_PATH ${ROOT_PATH}/wdc)
cmake_print_variables(WDC_PATH)
add_subdirectory(${WDC_PATH})
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU") # todo: enable for Clang, when it will begin to support the stacktrace library
    add_subdirectory(tests)
endif()
